version: '3'

services:
  dbtest:
    hostname: postgres
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - database-sonarqube:

networks:
  database-sonarqube:
